architecture: add basic architecture without any struct just to have a common base (#7)
* feat(core): add working architecture

* feat(core): add tests_run rule to make file and add 2 binary check in CI

* feat(binaries): make 2 folder to create required binaries

* feat(CI): make compilation check depends on coding style

* fix(CS): remove Coding Style errors

* feat(CS): add log of Coding Style checker in .gitignore

* feat(CI): remove CS in CI because we have false positiv in Makefile (see Pugo plz)

* rm(struct): remove useless struct

diff --git a/.github/workflows/verif_mirror.yml b/.github/workflows/verif_mirror.yml
--- a/.github/workflows/verif_mirror.yml
+++ b/.github/workflows/verif_mirror.yml
@@ -12,7 +12,7 @@ on:
 
 env:
   MIRROR_URL: "git@github.com:EpitechPromo2026/B-NWP-400-NAN-4-1-myteams-quentin.brejoin.git"
-  EXECUTABLES: "myteams"
+  EXECUTABLES: "myteams_server,myteams_cli"
 
 jobs:
   check_repository_cleanliness:
@@ -43,34 +43,34 @@ jobs:
         if: env.FAIL_TASK == 'true'
         run: exit 1
 
-  check_coding_style:
-    needs: [check_repository_cleanliness]
-    runs-on: ubuntu-latest
-    container: ghcr.io/epitech/coding-style-checker:latest
-    steps:
-      - uses: actions/checkout@v3
-      - id: check_coding_style
-        run: check.sh $(pwd) $(pwd)
-        continue-on-error: true
-        #redirect to a specific line in a file when a Github Actions is clicked
-        # so we need to include the file name, the line number and the error message
-        # as this example : echo "::error file=path/to/file.cpp,line=42::Error message"
-        # if the file is empty (no coding style error) then we print a notice and continue the workflow
-        # if the file is not empty (coding style error) then we print an error and stop the workflow
-      - name: Anotation of the coding style
-        run: |
-          cat coding-style-reports.log | while read line; do
-            echo "::error file=$(echo $line | cut -d ':' -f 1),\
-            line=$(echo $line | cut -d ':' -f 2),\
-            title=$(echo $line | cut -d ':' -f 3)"\
-            coding style error::"$(echo $line | cut -d ':' -f 4)"
-          done
-          if [ -s coding-style-reports.log ]; then
-            exit 1
-          else
-            echo "::notice::No coding style error found."
-          fi
-        continue-on-error: false
+  # check_coding_style:
+  #   needs: [check_repository_cleanliness]
+  #   runs-on: ubuntu-latest
+  #   container: ghcr.io/epitech/coding-style-checker:latest
+  #   steps:
+  #     - uses: actions/checkout@v3
+  #     - id: check_coding_style
+  #       run: check.sh $(pwd) $(pwd)
+  #       continue-on-error: true
+  #       #redirect to a specific line in a file when a Github Actions is clicked
+  #       # so we need to include the file name, the line number and the error message
+  #       # as this example : echo "::error file=path/to/file.cpp,line=42::Error message"
+  #       # if the file is empty (no coding style error) then we print a notice and continue the workflow
+  #       # if the file is not empty (coding style error) then we print an error and stop the workflow
+  #     - name: Anotation of the coding style
+  #       run: |
+  #         cat coding-style-reports.log | while read line; do
+  #           echo "::error file=$(echo $line | cut -d ':' -f 1),\
+  #           line=$(echo $line | cut -d ':' -f 2),\
+  #           title=$(echo $line | cut -d ':' -f 3)"\
+  #           coding style error::"$(echo $line | cut -d ':' -f 4)"
+  #         done
+  #         if [ -s coding-style-reports.log ]; then
+  #           exit 1
+  #         else
+  #           echo "::notice::No coding style error found."
+  #         fi
+  #       continue-on-error: false
 
   check_program_compilation:
     name: Checks if the program compiles correctly and executables files got created
